# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defaults :
  - modulus_default
  - /arch/super_res_cfg@arch.super_res
  - /arch/pix2pix_cfg@arch.pix2pix
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: True
cuda_graphs: False # Graphs does not work with super res network

arch:
  super_res:
    scaling_factor: 4
  pix2pix:
    batch_norm: True
    n_downsampling: 1
    n_blocks: 9
    dimension: 3
    scaling_factor: 4

scheduler:
  decay_rate: 0.95
  decay_steps: 2000

optimizer:
  lr: 0.0001

training:
  rec_validation_freq: 250
  rec_constraint_freq: 250
  save_network_freq: 250
  print_stats_freq: 25
  max_steps : 20000

batch_size:
  train: 4
  valid: 4

custom:
  jhtdb:
    n_train: 512
    n_valid: 16
    domain_size: 128
    access_token: "edu.jhu.pha.turbulence.testing-201311" #Replace with your own token here

  loss_weights:
    U: 1.0
    dU: 0
    continuity: 0
    omega: 0.1
    enstrophy: 0
    strain: 0

